/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;

       

/**
 *
 * @author alexa
 */
public class BilderTillOrder extends javax.swing.JFrame {

    
    private InfDB idb;
    /**
     * Creates new form BilderTillOrder
     */
    public BilderTillOrder(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllComboBox(); //fyller combobox med tillgängliga orderID
    }
    
    private void fyllComboBox(){
        try { 
            jComboBox1.removeAllItems(); //rensar combox innan data läggs in
            jComboBox1.addItem("Välj OrderID"); 
            
            
            ArrayList<String> orderIDLista = idb.fetchColumn("SELECT OID FROM ordrar");
            for (String oid : orderIDLista) {
                jComboBox1.addItem("OrderID " + oid); //lägger till varje orderID som ett val comboboxen
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av orderID: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVisaBilder = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVisaBilder.setText("Visa bilder kopplade till order");
        btnVisaBilder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaBilderActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OrderID 1", "OrderID 2", "OrderID 3..." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(btnVisaBilder)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisaBilder)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisaBilderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaBilderActionPerformed
        String selectedItem = (String) jComboBox1.getSelectedItem(); //hämtar vald orderID från combobox
        
        if (selectedItem == null || selectedItem.equals("Välj OrderID")) { //säkerställer att en riktig order har valts
            JOptionPane.showMessageDialog(this, "Välj en giltig order först."); //felmeddelande visas om ingen order valts
            return;
        }
        
        String orderID = selectedItem.replace("OrderID ",  ""); //tar bort texten "OrderID " för att få fram endast ID:t
        
        try {
            ArrayList<HashMap<String, String>> bilder = idb.fetchRows(
            "SELECT p.bild, p.Namn FROM försäljning f " +
            "JOIN produkt p ON f.ProduktID = p.ProduktID " +
            "WHERE f.OID = " + orderID); //hämtar bilder och produktnamn kopplat till orderID
            
        if (bilder.isEmpty()){
            JOptionPane.showMessageDialog(this, "Inga bilder kopplade till denna order."); //felmeddelande visas om det saknas bilder till order
            return;
        }
        
       JFrame bildFönster = new JFrame("Bilder för Order " + orderID); //skapar nytt fönster för bilder
       bildFönster.setSize(600,300);
       bildFönster.setLayout(new java.awt.FlowLayout()); 
       
       bildFönster.getContentPane().removeAll();
       
       for (HashMap<String, String> rad : bilder) {
    String bildVäg = rad.get("bild");
    String produktNamn = rad.get("Namn");

    if (bildVäg != null && !bildVäg.isEmpty()) {
        
        ImageIcon ikon = new ImageIcon(bildVäg); //laddar bilden från filväg
        Image bild = ikon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH); //skalar ner bilden tilll 200x200
        ImageIcon skaladIkon = new ImageIcon(bild);

        
        JLabel bildLabel = new JLabel(skaladIkon); //skapar jlabel med bilden

        
        JLabel namnLabel = new JLabel(produktNamn, JLabel.CENTER); //skapar jlabel med produktnamn

        
        JPanel produktPanel = new JPanel(); //skapar panel för bild och namn
        produktPanel.setLayout(new BorderLayout());
        produktPanel.add(bildLabel, BorderLayout.CENTER);
        produktPanel.add(namnLabel, BorderLayout.SOUTH);

        
        bildFönster.add(produktPanel); //lägger till produktpanelen i popup-fönstret
    }
}
       
       bildFönster.setVisible(true);
       bildFönster.revalidate();
       bildFönster.repaint();
       }
        
       catch (InfException e) {
           JOptionPane.showMessageDialog(this,"Fel vid hämtning av bilder: " + e.getMessage());
       }
    }//GEN-LAST:event_btnVisaBilderActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BilderTillOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BilderTillOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BilderTillOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BilderTillOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisaBilder;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
