/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author diyar
 */
public class Inloggning extends javax.swing.JFrame {
private InfDB idb;

    /**
     * Creates new form Inloggning
     */
    public Inloggning(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtemail = new javax.swing.JLabel();
        txtlösen = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        tflosenord = new javax.swing.JTextField();
        Btnloggain = new javax.swing.JButton();
        lblfelmeddelande = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtemail.setText("Email:");

        txtlösen.setText("Lösenord");

        Btnloggain.setText("Logga In");
        Btnloggain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnloggainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlösen, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblfelmeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnloggain, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfemail, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addComponent(tflosenord)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlösen)
                    .addComponent(tflosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblfelmeddelande)
                .addGap(18, 18, 18)
                .addComponent(Btnloggain, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnloggainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnloggainActionPerformed
   String email = tfemail.getText();
   String lösenord = tflosenord.getText();
   String sqlpid = "SELECT PID from personal WHERE Email = '" + email + "'";
   String sqlemail = "SELECT Email FROM personal WHERE Email = '" + email + "'";
   String sqllosen = "SELECT Lösenord FROM personal WHERE Email = '" + email + "'";
   String sqlbehörighet = "SELECT Behörighetsnivå FROM personal WHERE Email = '" + email + "'";
   String dbemail = null;
   String dblosen = null;
    int dbbehörighet;  
    String dbpid = null;
    try{
        dbpid = idb.fetchSingle(sqlpid);
    } catch (InfException e){
        JOptionPane.showMessageDialog(this, e);
    }

try {
    dbemail = idb.fetchSingle(sqlemail);
} catch (InfException ex) {
    lblfelmeddelande.setText("Fel vid hämtning av data");
    return;
}

if (dbemail == null) {
    lblfelmeddelande.setText("Användarnamnet finns ej");
    return;
}

try {
    dblosen = idb.fetchSingle(sqllosen);
    dbbehörighet = Integer.parseInt(idb.fetchSingle(sqlbehörighet));
} catch (InfException ex) {
    lblfelmeddelande.setText("Fel vid hämtning av data");
    return;
} catch (NumberFormatException ex) {
    lblfelmeddelande.setText("Felaktigt format på behörighetsnivå");
    return;
}

if (lösenord.equals(dblosen)) {
    if (dbbehörighet == 2) { 
        new AdminMeny(idb, dbpid).setVisible(true);
    } else {
        new GuiHuvudmeny(idb).setVisible(true);
    }
} else {
    lblfelmeddelande.setText("Fel lösenord, försök igen.");
}

    }//GEN-LAST:event_BtnloggainActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Inloggning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnloggain;
    private javax.swing.JLabel lblfelmeddelande;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tflosenord;
    private javax.swing.JLabel txtemail;
    private javax.swing.JLabel txtlösen;
    // End of variables declaration//GEN-END:variables

}