/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


//som användare, ska kunna lägga till lagerförda produkter i en order genom en lista

package hattmakarna;

//1234
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.HashMap;


//123

/**
 *
 * @author Tyson
 */
public class LäggTillProduktIOrder extends javax.swing.JFrame {

    private InfDB idb;
    private DefaultTableModel modell; //modell för tabellen
    /**
     * Creates new form LäggTillProduktIOrder
     */
    public LäggTillProduktIOrder(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllTabell();
    }

    
    private void fyllTabell(){
        try {
            //hämtar alla produkter med sql fråga
            String sql = "SELECT p.Namn AS Namn, p.Pris AS Pris, l.Antal AS Antal, p.ProduktID AS ProduktID " + 
                         "FROM Produkt p JOIN LagerfördaHattar l ON p.ProduktID = l.ProduktID";
            
            //hämtar alla rader från databasen
            ArrayList<HashMap<String, String>> produkter = idb.fetchRows(sql);
            
            DefaultTableModel modell = new DefaultTableModel();
            modell.addColumn("Namn");
            modell.addColumn("Pris");
            modell.addColumn("Antal i lager");
            modell.addColumn("ProduktID");
            
            
            //lägger till varje produkt i tabellen
            for (HashMap<String, String> produkt : produkter) {
                modell.addRow(new Object[] {
                
                produkt.get("Namn"),
                String.valueOf(produkt.get("pris")),
                produkt.get("Antal"),
                produkt.get("ProduktID")
            });
           
        }
        
        tblProdukter.setModel(modell);

        } catch (InfException ex) {
        JOptionPane.showMessageDialog(null, "Fel vid hämtning av produkter");    
    }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdukter = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfOrderID = new javax.swing.JTextField();
        tfAntal = new javax.swing.JTextField();
        btnLaggTill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblProdukter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Namn", "Pris", "Antal i lager ", "ProduktID"
            }
        ));
        jScrollPane1.setViewportView(tblProdukter);

        jLabel1.setText("Lägg till lagerförda produkter i listan ");

        jLabel2.setText("OrderID:");

        jLabel3.setText("Antal:");

        btnLaggTill.setText("Lägg till order");
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfOrderID)
                            .addComponent(tfAntal, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(96, 96, 96)
                        .addComponent(btnLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAntal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaggTill))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        
        try {
            int rad = tblProdukter.getSelectedRow(); //hämtar vald rad
            if (rad == -1) {
                JOptionPane.showMessageDialog(null, "Välj en produkt i listan");
                return;
                
            }
            
            // hämtar data från tabellen
            String produktID = tblProdukter.getValueAt(rad, 3).toString();
            String orderID = tfOrderID.getText().trim(); //hämtar order från textfält
            String antalStr = tfAntal.getText().trim(); //hämtar antal från textfält
            
            if (orderID.isEmpty() || antalStr.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Fyll i både OrderID och Antal");
                return;
                
            }
            
            int antal = Integer.parseInt(antalStr);
            
            //Kolla om produkt redan finns i order
            String kollaSQL = "SELECT * FROM Försäljning WHERE OID=" + orderID + " AND ProduktID=" + produktID;
            HashMap<String, String> resultat = idb.fetchRow(kollaSQL);
            
            if (resultat != null) {
                
                //produkten finns -> uppdatera antalet
                String nyAntalsSQL = "UPDATE Försäljning SET Antal = Antal + " + antal + " WHERE OID=" + orderID + " AND ProduktID=" + produktID;
                idb.update(nyAntalsSQL);
                } else { 
                //annars lägg till ny rad
                String insertSQL = "INSERT INTO Försäljning Values(" + orderID + "," + antal + ")";
                idb.insert(insertSQL);
                
            }
            
            //uppdatera lagret
            String minskaLagerSQL = "UPDATE LagerfördaHattar SET Antal = Antal -" + antal + " WHERE ProduktID=" + produktID;
            idb.update(minskaLagerSQL);
            
            JOptionPane.showMessageDialog(null, "Produkten lades till i ordern");
            fyllTabell(); //uppdaterar visning
            
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Antal måste vara en siffra");
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Fel vid databasåtkomst: " + e.getMessage());
                
            }
           
    }//GEN-LAST:event_btnLaggTillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LäggTillProduktIOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LäggTillProduktIOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LäggTillProduktIOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LäggTillProduktIOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LäggTillProduktIOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdukter;
    private javax.swing.JTextField tfAntal;
    private javax.swing.JTextField tfOrderID;
    // End of variables declaration//GEN-END:variables
}
