
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author seansiik
 */
public class SkapaOrder extends javax.swing.JFrame {
    
    
    private InfDB idb;

    /**
     * Creates new form SkapaOrder
     */
    public SkapaOrder(InfDB idb) {
        initComponents();
        this.idb = idb;    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableOrder1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        lblKundID1 = new javax.swing.JLabel();
        lblDatum1 = new javax.swing.JLabel();
        tfStatus1 = new javax.swing.JTextField();
        tfID1 = new javax.swing.JTextField();
        tfDatum1 = new javax.swing.JTextField();
        tfKundID1 = new javax.swing.JTextField();
        BtnLaggTill1 = new javax.swing.JButton();
        BtnAndra1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableOrder = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblKundID = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        tfStatus = new javax.swing.JTextField();
        tfID = new javax.swing.JTextField();
        tfDatum = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        BtnLaggTill = new javax.swing.JButton();
        ComboExpress = new javax.swing.JComboBox<>();
        lblExpress = new javax.swing.JLabel();
        BtnTillbaka = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Skapa Order");

        TableOrder1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Status", "Datum", "Kund ID"
            }
        ));
        jScrollPane2.setViewportView(TableOrder1);
        if (TableOrder1.getColumnModel().getColumnCount() > 0) {
            TableOrder1.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ny Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel3.setToolTipText("");

        lblID1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblID1.setText("ID");

        lblStatus1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblStatus1.setText("Status");

        lblKundID1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblKundID1.setText("Kund ID");

        lblDatum1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDatum1.setText("Datum");

        BtnLaggTill1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnLaggTill1.setForeground(new java.awt.Color(0, 0, 153));
        BtnLaggTill1.setText("Lägg till");
        BtnLaggTill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaggTill1ActionPerformed(evt);
            }
        });

        BtnAndra1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnAndra1.setForeground(new java.awt.Color(255, 0, 0));
        BtnAndra1.setText("Ändra");
        BtnAndra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAndra1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblDatum1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfDatum1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfKundID1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblID1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStatus1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKundID1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfID1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                        .addComponent(tfStatus1, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(BtnAndra1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(BtnLaggTill1)))
                        .addGap(55, 55, 55))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblID1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblStatus1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblDatum1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDatum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblKundID1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfKundID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAndra1)
                    .addComponent(BtnLaggTill1))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Skapa Order");

        TableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Status", "Datum", "Kund ID", "Express"
            }
        ));
        jScrollPane1.setViewportView(TableOrder);
        if (TableOrder.getColumnModel().getColumnCount() > 0) {
            TableOrder.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ny Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.add(jLabel2);

        lblID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblID.setText("ID");
        jPanel2.add(lblID);

        lblStatus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblStatus.setText("Status");
        jPanel2.add(lblStatus);

        lblKundID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblKundID.setText("Email");
        jPanel2.add(lblKundID);

        lblDatum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDatum.setText("Datum");
        jPanel2.add(lblDatum);
        jPanel2.add(tfStatus);
        jPanel2.add(tfID);
        jPanel2.add(tfDatum);
        jPanel2.add(tfEmail);

        BtnLaggTill.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnLaggTill.setForeground(new java.awt.Color(0, 0, 153));
        BtnLaggTill.setText("Lägg till");
        BtnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaggTillActionPerformed(evt);
            }
        });
        jPanel2.add(BtnLaggTill);

        ComboExpress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ComboExpress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ja", "Nej" }));
        ComboExpress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboExpressActionPerformed(evt);
            }
        });
        jPanel2.add(ComboExpress);

        lblExpress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblExpress.setText("Express");
        jPanel2.add(lblExpress);

        BtnTillbaka.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnTillbaka.setForeground(new java.awt.Color(0, 0, 153));
        BtnTillbaka.setText("Tillbaka");
        BtnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTillbakaActionPerformed(evt);
            }
        });
        jPanel2.add(BtnTillbaka);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaggTillActionPerformed

        //Hämtar data från textfälten
        String ID = tfID.getText();
        String Status = tfStatus.getText();
        String Datum = tfDatum.getText();
        String Email= tfEmail.getText();
        String expressStr = (String) ComboExpress.getSelectedItem();
        boolean Express = expressStr.equals("Ja");        
        
        // Kontroll: alla fält måste vara ifyllda
        if (ID.isEmpty() || Status.isEmpty() || Datum.isEmpty()|| Email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fyll i alla fält!", "Fel", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!validering.isNumerisk(ID)) {
        JOptionPane.showMessageDialog(this, "ID måste vara numeriskt.", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
        }

        if (!validering.isNotEmpty(Status)) {
        JOptionPane.showMessageDialog(this, "Status får inte vara tomt.", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
        }

        if (!validering.isValidDatum(Datum)) {
        JOptionPane.showMessageDialog(this, "Datum måste vara i formatet ÅÅÅÅ-MM-DD.", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
}

        

        try {
        
        String kontrollFraga = "SELECT * FROM kund WHERE Email = '" + Email + "'";
        
        HashMap<String, String> kund = null;
        
        kund = idb.fetchRow(kontrollFraga);

        if (kund == null || kund.isEmpty()) {
         new GuiValFönster(idb).setVisible(true);
        this.dispose(); 
        return;
       
    }
} catch (InfException e) {
    JOptionPane.showMessageDialog(this, "Fel vid kontroll av kund: " + e.getMessage(), "fel", JOptionPane.ERROR_MESSAGE);
    return;
}
        try{

        String sql = "INSERT INTO ordrar (OID, Status, Datum, express, Email)" + 
                     "VALUES ('" + ID + "', '" + Status + "', '" + Datum + "', " + Express + ",'" + Email + "')";

        idb.insert(sql);
        
                         

        // Lägger till raden i tabellen i GUI:t
        DefaultTableModel tableModel = (DefaultTableModel) TableOrder.getModel();
        tableModel.addRow(new Object[]{ID, Status, Datum, Email, Express});

         // Rensar textfälten efter insättning
        tfID.setText("");
        tfStatus.setText("");
        tfDatum.setText("");
        tfEmail.setText(""); 
        ComboExpress.setSelectedIndex(0);        
       
    } catch (InfException e) {
         JOptionPane.showMessageDialog(this, "Fel vid databasinsättning: " + e.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);
        
      }
     
    }//GEN-LAST:event_BtnLaggTillActionPerformed

    private void BtnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAndraActionPerformed

        //Hämtar vald rad i tabellen
        int selectedRow = TableOrder.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TableOrder.getModel();

        if (selectedRow != -1) { //Kontrollerar om en rad blivit vald

            // Hämtar nya värden från textFälten, men behåller den gamla infon om fältet är tomt
            String nyttID = tfID.getText().isEmpty() ? model.getValueAt(selectedRow, 0).toString() : tfID.getText();
            String nyStatus = tfStatus.getText().isEmpty() ? model.getValueAt(selectedRow, 1).toString() : tfStatus.getText();
            String nyttDatum = tfDatum.getText().isEmpty() ? model.getValueAt(selectedRow, 2).toString() : tfDatum.getText();
            String nyttKundID = tfEmail.getText().isEmpty() ? model.getValueAt(selectedRow, 3).toString() : tfEmail.getText();
            String nyExpressStr = (String) ComboExpress.getSelectedItem();
            boolean nyExpress = nyExpressStr.equals("Ja");
            
            // Validering av fält om användaren har ändrat dem
        if (!tfID.getText().isEmpty() && !validering.isNumerisk(nyttID)) {
            JOptionPane.showMessageDialog(this, "ID måste vara numeriskt.", "Fel", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!tfDatum.getText().isEmpty() && !validering.isValidDatum(nyttDatum)) {
            JOptionPane.showMessageDialog(this, "Datum måste vara i formatet ÅÅÅÅ-MM-DD.", "Fel", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!tfEmail.getText().isEmpty() && !validering.isNumerisk(nyttKundID)) {
            JOptionPane.showMessageDialog(this, "KundID måste vara numeriskt.", "Fel", JOptionPane.ERROR_MESSAGE);
            return;
        }

            // Uppdaterar tabellens modell med de nya värdena
            model.setValueAt(nyttID, selectedRow, 0);
            model.setValueAt(nyStatus, selectedRow, 1);
            model.setValueAt(nyttDatum, selectedRow, 2);
            model.setValueAt(nyttKundID, selectedRow, 3);
            model.setValueAt(nyExpress, selectedRow, 4);
      
            // Bekräftelsemeddelande
            JOptionPane.showMessageDialog(null, "Ordern har uppdaterats!", "Ändrat", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Om ingen rad är vald
            JOptionPane.showMessageDialog(null, "Välj en order att ändra!", "Fel", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_BtnAndraActionPerformed

    private void BtnLaggTill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaggTill1ActionPerformed

    }//GEN-LAST:event_BtnLaggTill1ActionPerformed

    private void BtnAndra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAndra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAndra1ActionPerformed

    private void BtnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTillbakaActionPerformed
        new Huvudmeny(idb,"").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTillbakaActionPerformed

    private void ComboExpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboExpressActionPerformed
           }//GEN-LAST:event_ComboExpressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkapaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkapaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkapaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkapaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new SkapaOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAndra1;
    private javax.swing.JButton BtnLaggTill;
    private javax.swing.JButton BtnLaggTill1;
    private javax.swing.JButton BtnTillbaka;
    private javax.swing.JComboBox<String> ComboExpress;
    private javax.swing.JTable TableOrder;
    private javax.swing.JTable TableOrder1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDatum1;
    private javax.swing.JLabel lblExpress;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblKundID;
    private javax.swing.JLabel lblKundID1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JTextField tfDatum;
    private javax.swing.JTextField tfDatum1;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfID1;
    private javax.swing.JTextField tfKundID1;
    private javax.swing.JTextField tfStatus;
    private javax.swing.JTextField tfStatus1;
    // End of variables declaration//GEN-END:variables
}

