/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;


/**
 *
 * @author Tyson
 */
public class TaBortLagerfordaVaror extends javax.swing.JFrame {

    private InfDB idb;
    private Map<String, String> modellIdMap = new HashMap<>();
    /**
     * Creates new form TaBortLagerfordaVaror
     */
    
    //konstruktorn tar emot en InfDB-objekt
    public TaBortLagerfordaVaror(InfDB idb) {
        initComponents();
        this.idb = idb;
        
        fyllModellerDropdown();
}

    //metod för att fylla comboboxen med lagerförda modeller
private void fyllModellerDropdown() {
    try{
        //rensar comboboxen på tidigare poster
        comboModeller.removeAllItems();
        comboModeller.addItem("-- Välj modell --");
        
        //hämtar alla lagerfördID från tabellen LagerfördaHattar
        ArrayList<String> rader = idb.fetchColumn("SELECT LagerfördID from LagerfördaHattar");
        
        for (String lagerID : rader) {
            String namn = idb.fetchSingle("SELECT Namn FROM Produkt WHERE ProduktID = " + "(SELECT ProduktID FROM LagerfördaHattar WHERE LagerfördID = " + lagerID + ")");
            String visningsnamn = namn + " (ID: " + lagerID + ")";
            modellIdMap.put(visningsnamn, lagerID);
            comboModeller.addItem(visningsnamn);
}
    } catch (InfException e){
        JOptionPane.showMessageDialog(this, "Kunde inte hämta modeller: " + e.getMessage());
        }

    }

   
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        lblVal = new javax.swing.JLabel();
        comboModeller = new javax.swing.JComboBox<>();
        BtnTaBort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setText("Ta bort lagerförd vara");

        lblVal.setText("Välj modell att ta bort");

        comboModeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModellerActionPerformed(evt);
            }
        });

        BtnTaBort.setText("Ta bort");
        BtnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTaBortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(comboModeller, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVal)
                    .addComponent(comboModeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(BtnTaBort)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Denna metod anropas när användaren trycker på "Ta bort"
    private void BtnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTaBortActionPerformed
        String valdModell = (String) comboModeller.getSelectedItem();
        
        if (valdModell == null || valdModell.equals("-- Vaäljmodell --")){
            JOptionPane.showMessageDialog(this, "Du måste välja en modell.");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Är du säker på att du vill ta bort modellen?", "Bekräfta borttagning", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
            
        }
        
        try{
            String lagerID = modellIdMap.get(valdModell);
            String produktID = idb.fetchSingle("SELECT ProduktID FROM LagerfördaHattar WHERELagerfördID = " + lagerID);
            
            idb.delete("DELETE FROM Produkt_material WHERE ProduktID = " + produktID);
            idb.delete("DELETE FROM LagerfördaHattar WHERE LagerfördID = " + lagerID);
            idb.delete("DELETE FROM Produkt WHERE ProduktID = " + produktID);
            
            JOptionPane.showMessageDialog(this, "Modellen har tagits bort.");
            fyllModellerDropdown();
        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid borttagning: " + e.getMessage());
            
        }
    }//GEN-LAST:event_BtnTaBortActionPerformed

    private void comboModellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModellerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboModellerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortLagerfordaVaror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortLagerfordaVaror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortLagerfordaVaror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortLagerfordaVaror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TaBortLagerfordaVaror().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTaBort;
    private javax.swing.JComboBox<String> comboModeller;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblVal;
    // End of variables declaration//GEN-END:variables
}
