/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author minna
 */
public class TilldelaOrder extends javax.swing.JFrame {
private static InfDB idb;
private String pid;
private String oid;

    /**
     * Creates new form TilldelaOrder
     */
    public TilldelaOrder(InfDB idb, String pid) {
        initComponents();
        this.idb = idb;
        this.pid = pid;
        fyllTabell();
    }
    
    
        private void fyllTabell() {       
        fyllOrderTotal();
        lblPID.setText(this.pid);
        }
        
        //Metod hämtar alla ordrar och fyller tabellen med dessa (fyller utan datumfiltrering)
    private void fyllOrderTotal() {
    try {
        String sqlFraga = "SELECT ordrar.OID, datum AS OrderDatum, Status AS OrderStatus, SUM(antal) AS AntalArtiklar, utförs_av "
                   + "FROM ordrar "
                   + "LEFT JOIN försäljning ON ordrar.OID = försäljning.OID "
                   + "WHERE Status != 'färdig' "
                + "GROUP BY ordrar.OID, datum, Status, utförs_av";
                ArrayList<HashMap<String, String>> resultat = idb.fetchRows(sqlFraga);

        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        model.setRowCount(0);

    if (resultat!=null){
    for (HashMap<String, String> rad : resultat) {
        
        model.addRow(new Object[]{
            rad.get("Datum"),
            rad.get("Status"),
            rad.get("AntalArtiklar"),
            rad.get("OID")
        });
    }
    }   
    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Fel vid hämtning av ordrar: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValjOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdukter = new javax.swing.JTable();
        btnTaHela = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblPID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnValjOrder.setText("Välj order");
        btnValjOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValjOrderMouseClicked(evt);
            }
        });
        btnValjOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValjOrderActionPerformed(evt);
            }
        });

        jLabel1.setText("Sök på specifik order efter beställningsdatum:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Välj en order för att kunna tilldela hel- eller del av order till dig själv.");

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Orderdatum", "Orderstatus", "Antal artiklar", "Ordernummer"
            }
        ));
        tblOrder.setToolTipText("");
        jScrollPane1.setViewportView(tblOrder);

        tblProdukter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Namn", "Antal", "Utförs av", "ID"
            }
        ));
        jScrollPane2.setViewportView(tblProdukter);

        btnTaHela.setText("Ta hela ordern");
        btnTaHela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaHelaActionPerformed(evt);
            }
        });

        btnDel.setText("Ta del av order");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        jLabel3.setText("Inloggad PID: ");

        lblPID.setText("PID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnValjOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPID)
                        .addGap(65, 65, 65))))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTaHela)
                    .addComponent(btnDel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblPID))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnValjOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnTaHela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDel)))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValjOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValjOrderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValjOrderMouseClicked

    private void btnValjOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValjOrderActionPerformed
        // TODO add your handling code here:
        // Visa vilka produkter som finns i ordern
        int row = tblOrder.getSelectedRow();
        
        this.oid = (String) tblOrder.getValueAt(row, 3);
        
        // använd oid för att hämta produkter
        String getInfo = "SELECT namn, antal, utförs_av, OrderProduktID FROM försäljning JOIN "
                + "produkt ON Försäljning.ProduktID = produkt.ProduktID WHERE Försäljning.OID = '" + this.oid + "'";
        
        ArrayList<HashMap<String, String>> info = new ArrayList<>();
        try{
            info = idb.fetchRows(getInfo);
        } catch (InfException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
       
        
        
        ((DefaultTableModel) tblProdukter.getModel()).setRowCount(0);
        
        
        
        if (info != null) {
            for (HashMap<String, String> rad : info) {
                 String utförare = rad.get("utförs_av");
        String getnamn = "SELECT Förnamn, Efternamn FROM personal WHERE PID = '" + utförare + "'";
        
        HashMap<String, String> dbnamn = new HashMap<>();
        
        try{
            dbnamn = idb.fetchRow(getnamn);
        } catch (InfException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        String namn = dbnamn.get("Förnamn") + " " + dbnamn.get("Efternamn");
                ((DefaultTableModel) tblProdukter.getModel()).addRow(new Object[]{
                    rad.get("Namn"),
                    rad.get("antal"),
                    namn,
                    rad.get("OrderProduktID")
                });
            }
        }

    }//GEN-LAST:event_btnValjOrderActionPerformed

    private void btnTaHelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaHelaActionPerformed
        // TODO add your handling code here:
        String sqlupdate = "UPDATE försäljning SET utförs_av = '" + pid + "' WHERE OID = '" +  this.oid + "'";
        
        try{
            idb.update(sqlupdate);
            JOptionPane.showMessageDialog(this, "Ansvar har tilldelats!");
        } catch (InfException e){
            JOptionPane.showMessageDialog(this, "1"+ e.getMessage());
        }
        
    }//GEN-LAST:event_btnTaHelaActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        int row = tblProdukter.getSelectedRow();
        
        String id = (String) tblProdukter.getValueAt(row, 3);

        String sqlUpdate = "UPDATE försäljning SET utförs_av = '" + pid + "' WHERE OrderProduktID = '" + id + "'";
        
        try{
            idb.update(sqlUpdate);
            JOptionPane.showMessageDialog(this, "Ansvar har tilldelats!");
        } catch (InfException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        
    }//GEN-LAST:event_btnDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TilldelaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TilldelaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TilldelaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TilldelaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TilldelaOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnTaHela;
    private javax.swing.JButton btnValjOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPID;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblProdukter;
    // End of variables declaration//GEN-END:variables
}
