/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author seansiik
 */
public class ÄndraHattbeskrivning extends javax.swing.JFrame {
    
    
    private InfDB idb;
  
    
    public ÄndraHattbeskrivning(InfDB idb) {
        initComponents();
        this.idb = idb; 
        loadData();
        tableBeskrivning.setAutoCreateRowSorter(true);
    }

    private void loadData() {
    try {
        String sql = "SELECT ProduktID, Beskrivning FROM produkt";
        ArrayList<HashMap<String, String>> result = idb.fetchRows(sql);

        DefaultTableModel model = (DefaultTableModel) tableBeskrivning.getModel();
        model.setRowCount(0); // Rensa tabellen

        for (HashMap<String, String> rad : result) {
            model.addRow(new Object[]{
                rad.get("ProduktID"),
                rad.get("Beskrivning")
            });
        }

    } catch (InfException e) {
        lblFelMed.setText("Fel vid hämtning av hattdata: " + e.getMessage());
    }
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnÄndra = new javax.swing.JButton();
        lblNyBeskrivning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBeskrivning = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBeskrivning = new javax.swing.JTable();
        lblFelMed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnÄndra.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnÄndra.setForeground(new java.awt.Color(255, 0, 51));
        BtnÄndra.setText("Ändra");
        BtnÄndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnÄndraActionPerformed(evt);
            }
        });

        lblNyBeskrivning.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNyBeskrivning.setText("Ny Beskrivning");

        taBeskrivning.setColumns(20);
        taBeskrivning.setRows(5);
        jScrollPane1.setViewportView(taBeskrivning);

        tableBeskrivning.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Beskrivning"
            }
        ));
        jScrollPane2.setViewportView(tableBeskrivning);
        if (tableBeskrivning.getColumnModel().getColumnCount() > 0) {
            tableBeskrivning.getColumnModel().getColumn(0).setMinWidth(0);
            tableBeskrivning.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableBeskrivning.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        lblFelMed.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFelMed, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnÄndra)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNyBeskrivning)
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFelMed)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNyBeskrivning, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnÄndra)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnÄndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnÄndraActionPerformed

    int row = tableBeskrivning.getSelectedRow();
    if (row != -1) {
        String produktID = tableBeskrivning.getValueAt(row, 0).toString();  // Kolumn 0 = ProduktID
        String nyBeskrivning = taBeskrivning.getText();

        if (nyBeskrivning != null && !nyBeskrivning.isEmpty()) {
            try {
                String sql = "UPDATE produkt SET Beskrivning = '" + nyBeskrivning + "' WHERE ProduktID = " + produktID;
                idb.update(sql);

                lblFelMed.setText("Beskrivning uppdaterad!");
                taBeskrivning.setText("");
                loadData(); // din metod för att uppdatera tabellen
            } catch (InfException e) {
                lblFelMed.setText("Fel vid uppdatering: " + e.getMessage());
            }
        } else {
            lblFelMed.setText("Beskrivning får inte vara tom.");
        }
    } else {
        lblFelMed.setText("Välj en produkt att uppdatera.");
    }

    }//GEN-LAST:event_BtnÄndraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÄndraHattbeskrivning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÄndraHattbeskrivning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÄndraHattbeskrivning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÄndraHattbeskrivning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ÄndraHattbeskrivning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnÄndra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFelMed;
    private javax.swing.JLabel lblNyBeskrivning;
    private javax.swing.JTextArea taBeskrivning;
    private javax.swing.JTable tableBeskrivning;
    // End of variables declaration//GEN-END:variables
}
